apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::647497469851:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-O3BJNQAJEGA2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::647497469851:role/UdacityFlaskDeployCBKubectlRole
      username: build      
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-02T04:09:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "961"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 648bf30d-f8bd-43e1-998c-a47382e974b9
