apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::AKIAZNQO3J6NRE32A7VX:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::AKIAZNQO3J6NRE32A7VX:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-30T17:12:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1025"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3fc70ff6-e0f9-4b66-bfb1-2d7d49196289
