apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::647497469851:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::647497469851:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-01T16:19:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "794"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1cd40c5d-4d06-4529-873b-6579bb48658d
